modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="drugeffects"
version="1.0.0"
displayName="Drug Effects"
updateJSONURL="http://my.versions/update.json"
displayURL="http://my.url/"
logoFile="logo.png"
credits="Antigravity"
authors="Antigravity"
description='''
Visual psychedelic effects.
'''

[[dependencies.drugeffects]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.drugeffects]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
